#This playbook installs a Metricbeat shipper on the DVWA web servers to share data with the Elk Stack.
# 1) Place this file in the /etc/ansible/roles directory of the Ansible control node.
# 2) Ensure the /etc/ansible/host file has the correct private IP addresses
#       of the target machines defined in the [webservers] section.
# 3) Ensure the /etc/ansible/ansible.cfg file has the "remote_user" and "log_path" defined
# 4) Ensure the /etc/ansible/metricbeat-config.yml file has the proper values See repository file comments.
# 5) Use the "ansible-playbook [playbook]" command to execute.
# - Created by George Gamarra
---
- name: Install and Launch Metricbeat
  hosts: webservers
  become: true
  tasks:

# Use command module
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

# Use command module
  - name: install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

# Use copy module
  - name: place in metricbeat config file
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

# Use command module
  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker

# Use command module
  - name: setup metric beat
    command: metricbeat setup

# Use command module
  - name: start metric beat
    command: service metricbeat start

